services:
  - type: web
    name: apijavamoney
    env: docker
    region: oregon
    plan: free
    branch: main
    rootDir: algamoney-api
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: algamoney-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: algamoney-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: algamoney-db
          property: password

databases:
  - name: algamoney-db
    databaseName: algamoneyapi
    user: algamoney
    plan: free
